### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by nbrady-techempower** [nbrady-techempower/today-i-learned#1]
- [ ] Try out some static site generators
- [ ] Add styling for code blocks
- [ ] AWS S3 Alias Certificate setup
- [ ] Filter tags
